apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-api
  template:
    metadata:
      labels:
        app: sensor-api
    spec:
      containers:
        - name: sensor-api
          image: # Replace this with your image's name
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-api-service
spec:
  selector:
    app: sensor-api
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
