apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-api
  template:
    metadata:
      labels:
        app: sensor-api
    spec:
      containers:
        - name: sensor-api
          image: registry.pi.local:5000/sensor-api:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: DB_USER
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: DB_PASSWD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: sensor-api-service
spec:
  selector:
    app: sensor-api
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
